
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtetryrdbntasdlutbdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZXRyeXJkYm50YXNkbHV0YmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTUzMTcsImV4cCI6MjA2MDU3MTMxN30.7w7TTVVtnlz6_fnBlq7nHjyk0PYp6pz_0D_OwByWbpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
