
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtetryrdbntasdlutbdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0ZXRyeXJkYm50YXNkbHV0YmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTUzMTcsImV4cCI6MjA2MDU3MTMxN30.7w7TTVVtnlz6_fnBlq7nHjyk0PYp6pz_0D_OwByWbpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Detect if we're in a sandbox preview environment
const isSandboxPreview = typeof window !== 'undefined' && 
  (window.location.hostname.includes('lovable.dev') || 
   window.location.hostname.includes('lovable.ai'));

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce', // Use PKCE flow, which works better in mobile and in iframe environments
    debug: isSandboxPreview // Enable auth debugging in sandbox preview
  }
});

// Log auth configuration on load for debugging
if (isSandboxPreview) {
  console.log("Supabase Auth Config:", {
    url: SUPABASE_URL,
    hasKey: !!SUPABASE_PUBLISHABLE_KEY,
    storage: "localStorage",
    location: window.location.origin,
    flowType: 'pkce',
    debug: true,
    cookieOptions: {
      sameSite: 'lax',
      secure: window.location.protocol === 'https:',
    }
  });
}
